version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
skip_tags: true
configuration: Release
clone_depth: 1
before_build:
  - ps: nuget restore -verbosity quiet
build:
  project: HeiBBSLeaderboard.sln
  verbosity: minimal
test: off
artifacts:
- path: .\bin\Release
  name: HeiBBSLeaderboard
deploy:
- provider: GitHub
  tag: 1.3
  auth_token:
    secure: wBUeC7f0SGZTu01Bl50RTSas9yizhxdAeqofugDSTpOoZFXOyzvP+X2OOAnaqIWz
  repository: PercyDan54/HeiBBSLeaderboard
  artifact: HeiBBSLeaderboard